// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-PXbeefEbAR9P0Od_oN0YtUVbSNRZrBM',
    appId: '1:397770795437:web:8acc646b55a07e0ca51924',
    messagingSenderId: '397770795437',
    projectId: 'flashchat-60d04',
    authDomain: 'flashchat-60d04.firebaseapp.com',
    storageBucket: 'flashchat-60d04.firebasestorage.app',
    measurementId: 'G-ZKSP2ND9N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABLxJIpW9czd_A6jfzc_ApJXeDfFcsw0o',
    appId: '1:397770795437:android:1bb44b8ad64b7edfa51924',
    messagingSenderId: '397770795437',
    projectId: 'flashchat-60d04',
    storageBucket: 'flashchat-60d04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB3kDvwOJiIZAz3aomK-B5WmWXt_9qH74',
    appId: '1:397770795437:ios:e749bea7de16dddca51924',
    messagingSenderId: '397770795437',
    projectId: 'flashchat-60d04',
    storageBucket: 'flashchat-60d04.firebasestorage.app',
    iosBundleId: 'co.appbrewery.flashChat',
  );
}
